//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MechSoftExample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meeting
    {
        public int MeetingID { get; set; }
        public string MeetingTopic { get; set; }
        public System.DateTime MeetingDate { get; set; }
        public System.TimeSpan MeetingStartTime { get; set; }
        public System.TimeSpan MeetingEndTime { get; set; }
        public string Participant { get; set; }
    }
}
